#!/bin/sh
#
# Fetch fivecalls data
#

case "$1" in
  start)
    if ! [ -c '/dev/ppp' ]; then mknod /dev/ppp c 108 0; fi

	echo "Starting PPP connection"
	/usr/bin/pon sim8xx
    sleep 2
    
    echo "Setting clock"
    /usr/bin/ntpdate pool.ntp.org 
    
    cd /opt/hotline
    echo "Fetching data"
    /usr/bin/python3 -m fivecalls.data
    
    echo "Tearing down PPP"
    /usr/bin/poff sim8xx
    
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
